import WiggleButton from '@/app/(front)/components/Inputs/WiggleButton'
import MouseShift from '@/app/(front)/components/Motion/MouseShift'
import { Metadata } from 'next'
import React from 'react'
import Image from 'next/image'

export const metadata: Metadata = {
    title: 'Stránka nebyla nalezena',
    description: 'Generated by create next app',
    robots: {
        index: false,
        follow: false,
    },
    openGraph: {
        title: 'TaisRugs | Koberec na zakázku',
        description: '',
        images: 'seo/open-graph.png',
    },
}

const E404 = () => {
    return (
        <section className='pageWrapper min-h-screen flex  justify-center items-center'>
            <MouseShift
                scale={2}
                className='w-full h-full absolute z-0 inset-0'
            >
                <div className='relative w-full h-full'>
                    <div className='absolute right-3/5 top-3/5 w-[15%] aspect-square bg-blue-500 rounded-4xl hover:scale-105 duration-300'>
                        <Image
                            src={'/images/Hero/1.png'}
                            alt={'Hero image'}
                            width={800}
                            height={800}
                            className='w-full h-full object-cover'
                        />
                    </div>

                    <div className='absolute left-5/6 top-1/6 w-[20%] aspect-square rounded-4xl hover:scale-105 duration-300'>
                        <Image
                            src={'/images/Hero/2.png'}
                            alt={'Hero image'}
                            width={800}
                            height={800}
                            className='w-full h-full object-cover'
                        />
                    </div>

                    <div className='absolute left-4/6 top-4/6 w-[14%] aspect-square  rounded-4xl hover:scale-105 duration-300'>
                        <Image
                            src={'/images/Hero/3.png'}
                            alt={'Hero image'}
                            width={800}
                            height={800}
                            className='w-full h-full object-cover'
                        />
                    </div>

                    <div className='absolute left-2/6 top-1/5 w-[17%] aspect-vid rounded-4xl hover:scale-105 duration-300'>
                        <Image
                            src={'/images/Hero/4.png'}
                            alt={'Hero image'}
                            width={800}
                            height={800}
                            className='w-full h-full object-cover'
                        />
                    </div>

                    <div className='absolute left-1/2 top-1/2 w-[18%] aspect-square  rounded-4xl hover:scale-105 duration-300'>
                        <Image
                            src={'/images/Hero/5.png'}
                            alt={'Hero image'}
                            width={800}
                            height={800}
                            className='w-full h-full object-cover'
                        />
                    </div>

                    <div className='absolute left-0 top-0 w-[18%] aspect-squar rounded-4xl hover:scale-105 duration-300'>
                        <Image
                            src={'/images/Hero/6.png'}
                            alt={'Hero image'}
                            width={800}
                            height={800}
                            className='w-full h-full object-cover'
                        />
                    </div>

                    <div className='absolute right-0 bottom-0 w-[15%] aspect-square rounded-4xl hover:scale-105 duration-300'>
                        <Image
                            src={'/images/Hero/7.png'}
                            alt={'Hero image'}
                            width={800}
                            height={800}
                            className='w-full h-full object-cover'
                        />
                    </div>

                    <div className='absolute left-0 bottom-0 w-[23%] aspect-squa rounded-4xl hover:scale-105 duration-300'></div>
                </div>
            </MouseShift>

            <div className='flex flex-col gap-4 items-center'>
                <h1>Ajaj, to se nepovedlo</h1>
                <p>Tato stránka není dostupná</p>
                <WiggleButton text='Domů' link={'/'} />
            </div>
        </section>
    )
}

export default E404
