import { Metadata } from 'next'
import React from 'react'

export const metadata: Metadata = {
    metadataBase: new URL('https://taisrugs.cz'),
    title: 'Work in Progress',
    description: 'Generated by create next app',
    keywords: [],
    twitter: {
        card: 'summary_large_image',
    },
    openGraph: {
        title: 'Motionlabs - Web development',
        description: '',
        images: '/brand/open-graph.png',
    },
}

const page = () => {
    return (
        <div className='w-full h-[100dvh] flex justify-center items-center'>
            <h1>In progress...</h1>
        </div>
    )
}

export default page
