import type { Metadata } from 'next'
import { Geist_Mono, Poppins } from 'next/font/google'
import './globals.css'
import localFont from 'next/font/local'
import Navigation from '@/components/Layout/Navigation/Navigation'
import Footer from '@/components/Layout/Footer/Footer'
import ReactLenis from 'lenis/react'

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

const poppins = Poppins({
    variable: '--font-poppins',
    weight: ['400'],
    subsets: ['latin'],
})

const Daffiys = localFont({
    src: '../assets/fonts/SuperMatcha.ttf',
    variable: '--font-daffiys',
})

export const metadata: Metadata = {
    title: {
        default: 'Domů | Tais Rugs',
        template: '%s | Tais Rugs',
    },
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <ReactLenis root options={{ lerp: 0.1, duration: 1.5 }}>
                <body
                    className={`${geistMono.variable} ${poppins.className}  ${Daffiys.variable} antialiased flex flex-col items-center min-h-screen justify-between px-4`}
                >
                    <Navigation></Navigation>

                    <main className='w-full flex-1 flex justify-center'>
                        {children}
                    </main>

                    <Footer></Footer>
                </body>
            </ReactLenis>
        </html>
    )
}
