import type { Metadata } from 'next'
import { Poppins, Lilita_One } from 'next/font/google'
import './globals.css'
import Navigation from '@/components/Layout/Navigation/Navigation'
import Footer from '@/components/Layout/Footer/Footer'
import ReactLenis from 'lenis/react'

const poppins = Poppins({
    variable: '--font-poppins',
    weight: ['400'],
    subsets: ['latin'],
})

const archivo = Lilita_One({
    variable: '--font-archivo',
    weight: ['400'],
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: {
        default: 'Domů | Tais Rugs',
        template: '%s | Tais Rugs',
    },
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='cs'>
            <ReactLenis root options={{ lerp: 0.1, duration: 1.5 }}>
                <body
                    className={`${poppins.className}  ${archivo.variable} antialiased flex flex-col items-center min-h-screen justify-between`}
                >
                    <Navigation></Navigation>

                    <main className='w-full flex-1 flex justify-center z-10'>
                        {children}
                    </main>

                    <Footer></Footer>
                </body>
            </ReactLenis>
        </html>
    )
}
