import WiggleButton from '@/components/Inputs/WiggleButton'
import ContactUs from '@/components/Layout/Contact/ContactUs'
import ButtonHeading from '@/components/UI/ButtonHeading'
import { Metadata } from 'next'
import React from 'react'

import bgImg from '@/../public/LogoStroke.svg'
import Hero from '@/components/Sections/KoberecNaZakazku/Hero'

export const metadata: Metadata = {
    title: 'Koberec na zakázku',
    description: 'Generated by create next app',
    openGraph: {
        title: 'TaisRugs | Koberec na zakázku',
        description: '',
        images: 'seo/open-graph.png',
    },
}

const KoberecNaZakazku = () => {
    return (
        <div
            className='min-h-[100vh] pb-12 w-full pageWrapper'
            style={{
                backgroundImage: `url(${bgImg.src})`,
                backgroundRepeat: 'no-repeat',
                backgroundPosition: '195% 16%',
                backgroundSize: '80%',
                backgroundAttachment: 'fixed',
            }}
        >
            <Hero />

            <ContactUs />
        </div>
    )
}

export default KoberecNaZakazku
